SET @DB_VERSION = "uts_modern_v1";
CREATE DATABASE IF NOT EXISTS @DB_VERSION;
GRANT ALL privileges ON @DB_VERSION.* TO 'modern'@localhost;
FLUSH PRIVILEGES;
use @DB_VERSION;
CREATE TABLE `customer_requests` (
	`id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	`first_name` VARCHAR(50) NULL DEFAULT NULL,
	`last_name` VARCHAR(50) NULL DEFAULT NULL,
	`company` VARCHAR(50) NULL DEFAULT NULL,
	`request` VARCHAR(2048) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`submit_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
